### PR TITLE
feat: update versioneer

### PR DESCRIPTION
**Pull request by sanjayankur31**
A new release would be very useful with this. Older versions of versioneer do not work on py3.12:

```
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 488, in run_setup
    self).run_setup(setup_script=setup_script)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 11, in <module>
  File "/builddir/build/BUILD/gcsfs-2023.6.0/versioneer.py", line 1524, in get_version 
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/gcsfs-2023.6.0/versioneer.py", line 1451, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/gcsfs-2023.6.0/versioneer.py", line 346, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

### CODE REVIEW

**Comment by martindurant** [comment]
Would also be happy to see a move away from versioneer to setuptools-scm

**Comment by martindurant** [comment]
You can either allow black to reformat stuff, or exclude the two version files from consideration to make the lint CI happy.
